import Link from "next/link";
import { mediaArchive } from "@/data/media";
import { MediaCard } from "@/components/MediaCard";
export default function Home(){return <main>
<section className="hero"><div className="container"><div className="hero-kicker"><span>✦</span> DAY STAR MINISTRIES • BASSETT, VIRGINIA</div><h1>A place to connect with Christ—and with one another.</h1><p>Come as you are. Worship with us, grow in grace, find meaningful connection, and discover ways to serve our community together.</p><div className="actions"><Link className="button" href="/im-new">Plan Your Visit</Link><Link className="button secondary" href="/watch">Watch & Pray With Us</Link></div></div></section>
<div className="service-strip"><div className="container"><div><strong>Sunday School</strong><br/>9:00 AM</div><div><strong>Sunday Worship</strong><br/>10:00 AM</div><div><strong>Sunday Evening</strong><br/>6:00 PM</div><div><strong>Wednesday Study</strong><br/>7:00 PM</div></div></div>
<section className="section c3-feature"><div className="c3-mark">C³</div><div className="container"><div className="eyebrow">Connection, Multiplied</div><h2>Coffee • Conversation • Christ</h2><p className="lead"><strong>C³ is a simple invitation to meaningful connection.</strong> Coffee is optional. Conversation opens the door. Christ stays at the center—and what one person carries can become encouragement, wisdom, service, and connection for someone else.</p><div className="pathway"><div><span>☕</span>Coffee</div><div><span>💬</span>Conversation</div><div><span>✝</span>Christ</div><div><span>♡</span>Community</div><div><span>∞</span>Connection</div></div><div className="actions"><Link className="button" href="/connect">Discover C³</Link><Link className="button secondary" href="/stories">Share Your Story</Link></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">Our Vision</div><h2>Connect. Grow. Serve.</h2><div className="grid"><div className="card"><h3>Connect</h3><p>Connect people to Christ and create room for genuine relationships across generations and beyond church walls.</p></div><div className="card"><h3>Grow</h3><p>Grow together in grace through worship, prayer, Scripture, testimony, conversation, and shared experience.</p></div><div className="card"><h3>Serve</h3><p>Notice needs, discover gifts, make connections, and serve our community for God’s glory.</p></div></div></div></section>
<section className="section alt"><div className="container"><div className="eyebrow">Worship & Prayer</div><h2>Watch. Pray. Revisit.</h2><p className="lead">Sunday worship and Tuesday Night Prayer Live belong in one easy place so a missed moment can become a connection later.</p><div className="grid two">{mediaArchive.slice(0,2).map(i=><MediaCard key={i.slug} item={i}/>)}</div><div className="actions"><Link className="button" href="/watch">Open Media Archive</Link><Link className="button secondary" href="/prayer">Request Prayer</Link></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">Outreach in Action</div><h2>See a need. Make a connection. Join a mission.</h2><p className="lead">Day Star’s outreach is being built as one connection engine with many expressions—from C³ and Community Care to skills, service, stories, partnerships, and future church-to-church connections.</p><div className="grid"><div className="card"><div className="pill">Community Care</div><h3>Closet & Pantry</h3><p>Take what you need. Give what you can. No cost. A dignity-first place for clothing, pantry support, and connection.</p></div><div className="card"><div className="pill">Skills & Service</div><h3>Gifts Become Service</h3><p>Discover what people can teach, want to learn, and can contribute to practical community projects.</p></div><div className="card"><div className="pill">Day Star Stories</div><h3>Real people. Real stories. A living God.</h3><p>Testimony and impact stories—shared only with review and permission—help one connection create another.</p></div></div></div></section>
</main>}