import Link from "next/link";
import { site } from "@/lib/site";
export default function Connect(){return <main>
<section className="page-hero page-hero-c3"><div className="container"><div className="eyebrow light">C³ • Connection, Multiplied</div><h1>Coffee • Conversation • Christ</h1><p>Building meaningful intergenerational friendships through fellowship—with room for anyone who needs connection, not only those already inside the church.</p></div></section>
<section className="section c3-feature"><div className="container c3-split"><div><div className="eyebrow">Coffee optional. Connection essential.</div><h2>One connection creates another.</h2><p className="lead">C³ begins simply: people sit down, talk, listen, encourage, pray, and learn from one another. Christ remains at the center while community grows around the conversation.</p>
<div className="pathway"><div><span>☕</span>Coffee</div><div><span>💬</span>Conversation</div><div><span>✝</span>Christ</div><div><span>♡</span>Community</div><div><span>∞</span>Connection</div></div></div>
<div className="c3-visual"><div className="c3-cup">C³</div><div className="c3-star">✦</div><p>One connection creates another.<br/>One conversation creates another.<br/>One act of service creates another.</p></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">How It Works</div><h2>Start small. Let it multiply.</h2><div className="grid"><div className="feature-card"><div className="feature-icon">1</div><h3>Connect</h3><p>We help create an intentional relationship or conversation across generations and life experiences.</p></div><div className="feature-card"><div className="feature-icon">2</div><h3>Converse</h3><p>Listen, share, encourage, pray, and discover what each person carries.</p></div><div className="feature-card"><div className="feature-icon">3</div><h3>Multiply</h3><p>What was learned becomes encouragement, service, mentoring, or another meaningful connection.</p></div></div>
<div className="cta-band"><div><span>C³ PILOT</span><h3>Interested in being part of the first connections?</h3></div><a className="button" href={site.phoneHref}>Call Day Star</a></div>
</div></section></main>}